coverage:
  round: down 
  range: 65...100

ignore:
  - hatchet/tests/*
  - docs/examples/*

comment:
  layout: "header, diff, changes, tree"
  behavior: new
  require_changes: false
  require_base: false
  require_head: true
  after_n_builds: 5
