name: pull request review auto label

on:
  pull_request_review:
    types: [submitted]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Auto Label if Approved
        if: github.event.review.state == 'approved'
        # There's a bug in master of this tool that causes action to fail.
        # TODO Replace with newer version when bug is fixed
        uses: andymckay/labeler@1.0.3
        with:
          add-labels: 'status: approved, status: ready to merge'
          remove-labels: 'status: ready for review'
      - name: Auto Label if Revisions Needed
        if: github.event.review.state == 'changes_requested'
        # There's a bug in master of this tool that causes action to fail.
        # TODO Replace with newer version when bug is fixed
        uses: andymckay/labeler@1.0.3
        with:
          add-labels: 'status: revisions needed'
          remove-labels: 'status: ready for review'
